volumes:
   gitb-repo:
   gitb-dbdata:
   letsencrypt:
   certbot-www:

services:
   gitb-redis:
      image: isaitb/gitb-redis
      container_name: itb-redis
      restart: unless-stopped
   gitb-mysql:
      image: isaitb/gitb-mysql
      container_name: itb-mysql
      restart: unless-stopped
      volumes:
       - gitb-dbdata:/var/lib/mysql
      healthcheck:
       test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
       interval: 3s
       retries: 50
   gitb-srv:
      image: isaitb/gitb-srv
      container_name: itb-srv
      restart: unless-stopped
      environment:
       - CALLBACK_ROOT_URL=http://localhost:8080/itbsrv
      ports:
       - "8080:8080"
   gitb-ui:
      image: isaitb/gitb-ui
      container_name: itb-ui
      restart: unless-stopped
      ports:
       - "9000:9000"
      environment:
       - THEME=ec
       - AUTOMATION_ENABLED=true
      volumes:
       - gitb-repo:/gitb-repository
      depends_on:
       gitb-redis:
         condition: service_started
       gitb-mysql:
         condition: service_healthy
       gitb-srv:
         condition: service_started
   gitb-proxy:
      image: nginx:1.25-alpine
      container_name: itb-proxy
      restart: unless-stopped
      depends_on:
         gitb-ui:
            condition: service_started
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./nginx/conf.d/gitb.conf:/etc/nginx/conf.d/default.conf:ro
         - ./nginx/start-proxy.sh:/etc/nginx/start-proxy.sh:ro
         - letsencrypt:/etc/letsencrypt
         - certbot-www:/var/www/certbot
      entrypoint: ["/bin/sh","/etc/nginx/start-proxy.sh"]

   certbot:
      image: certbot/certbot
      container_name: itb-certbot
      restart: unless-stopped
      environment:
         - CERTBOT_EMAIL=engineering@helina.africa
      depends_on:
         gitb-proxy:
            condition: service_started
      entrypoint: ["/bin/sh","/opt/certbot/run.sh"]
      volumes:
         - letsencrypt:/etc/letsencrypt
         - certbot-www:/var/www/certbot
         - ./certbot/run.sh:/opt/certbot/run.sh:ro
         - /var/run/docker.sock:/var/run/docker.sock:ro